# _config.yml

# Site settings
title: Davide's Personal Website
description: A Test Engineer's space with a background in Aerospace Engineering, exploring Aviation, Automotive, Mechanical Watches, Videogames, Manga, Movies, Music, and Art.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dzxx1.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-minimal # You can replace this with the name of your preferred theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social settings
author:
  name: Davide
  email: your.email@example.com
  twitter_username: your_twitter_username
  github_username: your_github_username

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
